# Generated by Django 5.2.5 on 2025-09-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Координаты: широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Координаты: долгота')),
            ],
        ),
    ]
