# Generated by Django 5.2.5 on 2025-09-08 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name': 'координаты', 'verbose_name_plural': 'координаты'},
        ),
        migrations.AddField(
            model_name='coordinate',
            name='coordinate_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='дата и время записи координат'),
            preserve_default=False,
        ),
    ]
