# Generated by Django 5.2.5 on 2025-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_alter_coordinate_options_coordinate_coordinate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
