# Generated by Django 5.2.5 on 2025-08-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products', through='foodcartapp.OrderProduct', to='foodcartapp.product'),
        ),
    ]
