# Generated by Django 5.2.5 on 2025-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Заявка обрабатывается', 'Заявка обрабатывается'), ('Готовим ваш торт', 'Готовим заказ'), ('Продукт в пути', 'Заказ в пути'), ('Продукт у вас', 'Заказ у вас')], default='Заявка обрабатывается', max_length=25, verbose_name='статус заказа'),
        ),
    ]
