# Generated by Django 5.2.5 on 2025-09-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Готовится', 'Готовится'), ('В пути', 'В пути'), ('Завершен', 'Завершен')], db_index=True, default='Необработанный', max_length=25, verbose_name='статус заказа'),
        ),
    ]
