# Generated by Django 5.2.5 on 2025-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_call_date_order_delivery_date_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], db_index=True, default='Электронно', max_length=25, verbose_name='способ оплаты'),
        ),
    ]
